export const NOTIFICATION_TYPE = {
  NEW_BOOKING: 'BOOKING MỚI',
  REFUND: 'HOÀN TIỀN',
  COMPLETED: 'HOÀN THÀNH',
  TOPUP: 'NẠP TIỀN',
  DELIVERY: 'ĐANG DI CHUYỂN',
  CONFIRMED: 'XÁC NHẬN',
  WORKING: 'ĐANG LÀM',
  CANCELLED_BY_CUSTOMER: 'HỦY BỞI KHÁCH',
  CANCELLED_BY_KLEENIX: 'HỦY BỞI KLEENIX',
  FEEDBACK: 'PHẢN HỒI',
  GENERAL: 'THÔNG BÁO CHUNG',
}